const words = [
    { english: " afflicted", hebrew: "נגוע" },
    { english: "abdomen", hebrew: "בטן" },
    { english: "aberrant", hebrew: "לא תקינה" },
    { english: "Apparently", hebrew: "כנראה" },
    { english: "apt", hebrew: "מתאים" },
    { english: "arouses", hebrew: "מעורר" },
    { english: "attenuated", hebrew: "מדוכא / מדכא" },
    { english: "bacterium", hebrew: "חיידק" },
    { english: "barley", hebrew: "שעורה" },
    { english: "compartments", hebrew: "תאים" },
    { english: "constipation", hebrew: "עצירות" },
    { english: "cradles of civilization", hebrew: "הציוויליזציה הראשונה" },
    { english: "culprit", hebrew: "עבריין" },
    { english: "diabetes", hebrew: "סוכרת" },
    { english: "diarrhea", hebrew: "שלשול" },
    { english: "domesticate", hebrew: "לביית" },
    { english: "emaciated", hebrew: "כחוש" },
    { english: "grooves", hebrew: "חריצים/שקעים" },
    { english: "grout", hebrew: "חומר מילוי / רובה" },
    { english: "gut", hebrew: "מעי" },
    { english: "harbor", hebrew: "נמל/נושאים" },
    { english: "hyperactivity", hebrew: "חריפה/היפראקטיבי" },
    { english: "ilk", hebrew: "דומיו/ראשית" },
    { english: "illuminating", hebrew: "מאיר" },
    { english: "Impaired", hebrew: "לקוי" },
    { english: "impairs", hebrew: "פוגע" },
    { english: "inducing", hebrew: "גורם" },
    { english: "inert ", hebrew: "אדיש/עצל" },
    { english: "inhibitor", hebrew: "מעכב" },
    { english: "intestinal", hebrew: "מעי/פנימי" },
    { english: "intestinal lining", hebrew: "רירית המעי" },
    { english: "meshwork", hebrew: "רשת" },
    { english: "nomadic", hebrew: "נוד/נודד" },
    { english: "notoriously", hebrew: "ידוע לשמצה" },
    { english: "pediatrician", hebrew: "רופא ילדים" },
    { english: "permeable", hebrew: "חדיר" },
    { english: "predisposing", hebrew: "נטייה" },
    { english: "predisposition", hebrew: "נטיה קדומה/ נטייה אחרת" },
    { english: "prescription", hebrew: "מרשם" },
    { english: "propensity", hebrew: "נטייה" },
    { english: "realization", hebrew: "התממשות" },
    { english: "recurrent", hebrew: "חוזר ונשנה" },
    { english: "rye", hebrew: "שיפון" },
    { english: "sclerosis", hebrew: "טרשת" },
    { english: "secreted", hebrew: "מופרש" },
    { english: "seizures", hebrew: "פרכוסים" },
    { english: "seminal", hebrew: "מיתולוגי / פורץ דרך" },
    { english: "sham", hebrew: "בלוף" },
    { english: "shunting", hebrew: "העברה" },
    { english: "strands", hebrew: "סיבים" },
    { english: "suppress", hebrew: "לדכא" },
    { english: "susceptibility", hebrew: "רגישות" },
    { english: "tiles", hebrew: "אריחים" },
    { english: "tolerability", hebrew: "סבילות" },
    { english: "vomiting", hebrew: "הקאה" },
    { english: "wreaks havoc", hebrew: "זורע הרס" },
    { english: "yeast", hebrew: "שמרים/עילנים" },
    { english: "surmised", hebrew: "הניח/שיער" },
    { english: "eliciting", hebrew: "גירוי" },
    { english: "hallmark", hebrew: "סימן היכר" },
    { english: "relieved", hebrew: "הקלה" },
    { english: "spared", hebrew: "חסך/לוותר על" },
    { english: "outward signs", hebrew: "סימנים חיצוניים" },
    { english: "atypical", hebrew: "לא תיפוסי" },
    { english: "gobble up", hebrew: "בולעים" },
    { english: "sentinels", hebrew: "שומרים/זקיפים" },
    { english: "perusal", hebrew: "לעיון" },
    { english: "onset", hebrew: "התקפה" },
    { english: "sensitized", hebrew: "רגיש" },
    { english: "underpining", hebrew: "בסיס" },
];